# Generated by Django 4.2.10 on 2024-02-22 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0004_alter_identityprovider_custom_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data', models.TextField()),
                ('status_code', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.identityprovider')),
            ],
            options={
                'verbose_name': 'access identity',
                'verbose_name_plural': 'access identities',
            },
        ),
    ]
